//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_DECLARATIONS_METHODDECLARATION_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_DECLARATIONS_METHODDECLARATION_H_

class MethodDeclaration {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_DECLARATIONS_METHODDECLARATION_H_
