//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_DECLARATIONS_VARIABLEDECLARATION_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_DECLARATIONS_VARIABLEDECLARATION_H_

class VariableDeclaration {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_DECLARATIONS_VARIABLEDECLARATION_H_
