//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_METHODINVOCATION_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_METHODINVOCATION_H_

class MethodInvocation {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_METHODINVOCATION_H_
