#pragma once

#include "grammar/nterms_classes/class_declarations/ClassDeclaration.h"
#include "grammar/nterms_classes/class_declarations/ClassDeclarationList.h"
#include "grammar/nterms_classes/class_declarations/MainClass.h"

#include "grammar/nterms_classes/declarations/Declaration.h"
#include "grammar/nterms_classes/declarations/MethodDeclaration.h"
#include "grammar/nterms_classes/declarations/VariableDeclaration.h"
#include "grammar/nterms_classes/declarations/DeclarationList.h"

#include "grammar/nterms_classes/expressions/AccessToArrayElementExpression.h"
#include "grammar/nterms_classes/expressions/ArrayNewExpression.h"
#include "grammar/nterms_classes/expressions/ArrayLengthExpression.h"
#include "grammar/nterms_classes/expressions/BinaryOperatorExpression.h"
#include "grammar/nterms_classes/expressions/NewExpression.h"
#include "grammar/nterms_classes/expressions/Expression.h"
#include "grammar/nterms_classes/expressions/ExpressionList.h"
#include "grammar/nterms_classes/expressions/IdentExpression.h"
#include "grammar/nterms_classes/expressions/MethodInvocationExpression.h"
#include "grammar/nterms_classes/expressions/NotExpression.h"
#include "grammar/nterms_classes/expressions/NumberExpression.h"
#include "grammar/nterms_classes/expressions/ParenthesisExpression.h"
#include "grammar/nterms_classes/expressions/ThisExpression.h"
#include "grammar/nterms_classes/expressions/BoolExpression.h"

#include "grammar/nterms_classes/Lvalue/Lvalue.h"
#include "grammar/nterms_classes/Lvalue/SimpleLvalue.h"
#include "grammar/nterms_classes/Lvalue/ArrayElementLvalue.h"

#include "grammar/nterms_classes/statements/AssertStatement.h"
#include "grammar/nterms_classes/statements/AssignmentStatement.h"
#include "grammar/nterms_classes/statements/IfStatement.h"
#include "grammar/nterms_classes/statements/IfElseStatement.h"
#include "grammar/nterms_classes/statements/LocalVariableDeclarationStatement.h"
#include "grammar/nterms_classes/statements/MethodInvocationStatement.h"
#include "grammar/nterms_classes/statements/ReturnStatement.h"
#include "grammar/nterms_classes/statements/ScopeStatement.h"
#include "grammar/nterms_classes/statements/SoutStatement.h"
#include "grammar/nterms_classes/statements/Statement.h"
#include "grammar/nterms_classes/statements/StatementList.h"
#include "grammar/nterms_classes/statements/WhileStatement.h"

#include "grammar/nterms_classes/type/Type.h"
#include "grammar/nterms_classes/type/SimpleType.h"
#include "grammar/nterms_classes/type/ArrayType.h"

#include "grammar/nterms_classes/BinaryOperator.h"
#include "grammar/nterms_classes/Formal.h"
#include "grammar/nterms_classes/FormalList.h"
#include "grammar/nterms_classes/TypeIdentifier.h"
#include "grammar/nterms_classes/LocalVariableDeclaration.h"
#include "grammar/nterms_classes/MethodInvocation.h"
#include "grammar/nterms_classes/Program.h"