//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_CLASS_DECLARATIONS_CLASSDECLARATION_H_
#define COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_CLASS_DECLARATIONS_CLASSDECLARATION_H_

class ClassDeclaration {};

#endif // COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_CLASS_DECLARATIONS_CLASSDECLARATION_H_
