//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_CLASS_DECLARATIONS_CLASSEXTENDSDECLARATION_H_
#define COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_CLASS_DECLARATIONS_CLASSEXTENDSDECLARATION_H_

class ClassExtendsDeclaration {};

#endif // COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_CLASS_DECLARATIONS_CLASSEXTENDSDECLARATION_H_
