//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_MAINCLASS_H_
#define COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_MAINCLASS_H_

class MainClass {};

#endif // COMPILERS_03_PARSERS_WITH_AST_NTERMS_CLASSES_MAINCLASS_H_
