//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_SIMPLETYPE_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_SIMPLETYPE_H_

class SimpleType {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_SIMPLETYPE_H_
