//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_TYPE_TYPE_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_TYPE_TYPE_H_

class Type {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_TYPE_TYPE_H_
