//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_ASSIGNMENTSTATEMENT_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_ASSIGNMENTSTATEMENT_H_

class AssignmentStatement {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_ASSIGNMENTSTATEMENT_H_
