//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_IFELSESTATEMENT_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_IFELSESTATEMENT_H_

class IfElseStatement {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_IFELSESTATEMENT_H_
