//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_IFSTATEMENT_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_IFSTATEMENT_H_

class IfStatement {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_IFSTATEMENT_H_
