//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_LOCALVARIABLEDECLARATIONSTATEMENT_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_LOCALVARIABLEDECLARATIONSTATEMENT_H_

class LocalVariableDeclarationStatement {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_LOCALVARIABLEDECLARATIONSTATEMENT_H_
