//
// Created by artyom on 15.03.2020.
//

#ifndef COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_SCOPESTATEMENT_H_
#define COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_SCOPESTATEMENT_H_

class ScopeStatement {};

#endif // COMPILERS_03_PARSERS_WITH_AST_CLASSES_STATEMENTS_SCOPESTATEMENT_H_
